#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=scripts/dotfiles/lib.sh
source "${SCRIPT_DIR}/lib.sh"

check_home=""

cleanup() {
  [[ -z "${check_home}" ]] || rm -rf "${check_home}"
}

assert_empty_file() {
  local path="$1"

  if [[ ! -f "${path}" ]]; then
    error "expected file was not created: ${path}"
    return 1
  fi

  if [[ -s "${path}" ]]; then
    error "expected file to be empty: ${path}"
    return 1
  fi
}

assert_file_equals() {
  local path="$1"
  local expected="$2"
  local actual

  if [[ ! -f "${path}" ]]; then
    error "expected file was not created: ${path}"
    return 1
  fi

  actual="$(cat "${path}")"
  if [[ "${actual}" != "${expected}" ]]; then
    error "unexpected file content: ${path}"
    diff -u <(printf '%s\n' "${expected}") <(printf '%s\n' "${actual}") >&2 || true
    return 1
  fi
}

run_generator() {
  HOME="${check_home}" "${DOTFILES_ROOT}/install/common/git-signing.sh" >/dev/null 2>&1
}

check_without_key() {
  check_home="$(mktemp -d)"
  run_generator

  assert_empty_file "${check_home}/.config/git/config-composio-signing"
  assert_empty_file "${check_home}/.config/git/allowed_signers"
  rm -rf "${check_home}"
  check_home=""
}

check_with_default_key() {
  local expected_config
  local expected_signer

  check_home="$(mktemp -d)"
  mkdir -p "${check_home}/.ssh"
  printf 'ssh-ed25519 AAAATEST default-comment\n' >"${check_home}/.ssh/id_ed25519.pub"

  run_generator

  expected_config="$(cat <<EOF
# Generated by dotfiles from local SSH public key state.

[user]
	signingKey = ${check_home}/.ssh/id_ed25519.pub

[gpg]
	format = ssh

[gpg "ssh"]
	allowedSignersFile = ~/.config/git/allowed_signers

[commit]
	gpgSign = true
EOF
)"
  expected_signer="alberto@composio.dev ssh-ed25519 AAAATEST"

  assert_file_equals "${check_home}/.config/git/config-composio-signing" "${expected_config}"
  assert_file_equals "${check_home}/.config/git/allowed_signers" "${expected_signer}"
  rm -rf "${check_home}"
  check_home=""
}

check_with_env_key() {
  local expected_signer
  local key_path

  check_home="$(mktemp -d)"
  mkdir -p "${check_home}/custom"
  key_path="${check_home}/custom/signing-key"
  printf 'ssh-ed25519 AAAAENV env-comment\n' >"${key_path}.pub"

  HOME="${check_home}" \
    GIT_SSH_SIGNING_KEY="${key_path}" \
    COMPOSIO_GIT_EMAIL="dev@example.com" \
    "${DOTFILES_ROOT}/install/common/git-signing.sh" >/dev/null 2>&1

  expected_signer="dev@example.com ssh-ed25519 AAAAENV"
  assert_file_equals "${check_home}/.config/git/allowed_signers" "${expected_signer}"
  rm -rf "${check_home}"
  check_home=""
}

main() {
  trap cleanup EXIT
  check_without_key
  check_with_default_key
  check_with_env_key
}

main "$@"
