#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -n "${DOTFILES_DEBUG:-}" ]]; then
  set -x
fi

readonly DEFAULT_COMPOSIO_GIT_EMAIL="alberto@composio.dev"
readonly GIT_CONFIG_DIR="${HOME}/.config/git"
readonly SIGNING_CONFIG_PATH="${GIT_CONFIG_DIR}/config-composio-signing"
readonly ALLOWED_SIGNERS_PATH="${GIT_CONFIG_DIR}/allowed_signers"

log() {
  printf '==> %s\n' "$*" >&2
}

candidate_public_key_paths() {
  local candidate

  for candidate in "${GIT_SSH_SIGNING_KEY:-}" "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    [[ -n "${candidate}" ]] || continue
    [[ "${candidate}" == *.pub ]] || candidate="${candidate}.pub"
    printf '%s\n' "${candidate}"
  done
}

detect_signing_key() {
  local candidate

  while IFS= read -r candidate; do
    if [[ -f "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done < <(candidate_public_key_paths)

  return 1
}

write_empty_signing_files() {
  mkdir -p "${GIT_CONFIG_DIR}"
  : >"${SIGNING_CONFIG_PATH}"
  : >"${ALLOWED_SIGNERS_PATH}"
}

write_signing_files() {
  local key_path="$1"
  local key_type
  local key_material
  local composio_git_email="${COMPOSIO_GIT_EMAIL:-${DEFAULT_COMPOSIO_GIT_EMAIL}}"

  read -r key_type key_material _ <"${key_path}" || true
  if [[ -z "${key_type:-}" || -z "${key_material:-}" ]]; then
    log "SSH public key is not usable for signing: ${key_path}"
    write_empty_signing_files
    return 0
  fi

  mkdir -p "${GIT_CONFIG_DIR}"
  cat >"${SIGNING_CONFIG_PATH}" <<EOF
# Generated by dotfiles from local SSH public key state.

[user]
	signingKey = ${key_path}

[gpg]
	format = ssh

[gpg "ssh"]
	allowedSignersFile = ~/.config/git/allowed_signers

[commit]
	gpgSign = true
EOF

  printf '%s %s %s\n' "${composio_git_email}" "${key_type}" "${key_material}" >"${ALLOWED_SIGNERS_PATH}"
}

main() {
  local key_path
  if key_path="$(detect_signing_key)"; then
    log "Writing Git SSH signing config from ${key_path}"
    write_signing_files "${key_path}"
  else
    log "No SSH public key found; clearing Git SSH signing config"
    write_empty_signing_files
  fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
